# Generated by Django 5.2 on 2025-04-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=300)),
                ('biome_type', models.CharField(max_length=50)),
                ('depth_range', models.IntegerField(default=0)),
                ('temp_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=300)),
                ('tool_type', models.CharField(max_length=100)),
                ('build_time', models.IntegerField()),
                ('attribute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=300)),
                ('velocity', models.CharField(max_length=300)),
                ('health', models.IntegerField()),
                ('acq_from', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('fauna_type', models.CharField(max_length=100)),
                ('attitude', models.CharField(max_length=50)),
                ('biomes', models.ManyToManyField(related_name='faunas_biomes', to='Subnautica.biomes')),
            ],
        ),
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attitude', models.CharField(max_length=50)),
                ('biomes', models.ManyToManyField(related_name='eggs_biomes', to='Subnautica.biomes')),
                ('fauna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subnautica.faunas')),
            ],
        ),
        migrations.CreateModel(
            name='Floras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('use', models.CharField(max_length=100)),
                ('attitude', models.CharField(max_length=100)),
                ('obtain_from', models.CharField(max_length=100)),
                ('growth_time', models.IntegerField()),
                ('biomes', models.ManyToManyField(related_name='floras_biomes', to='Subnautica.biomes')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('obtain_from', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('biomes', models.ManyToManyField(related_name='resources_biomes', to='Subnautica.biomes')),
            ],
        ),
        migrations.AddField(
            model_name='biomes',
            name='resources',
            field=models.ManyToManyField(related_name='biomes_resources', to='Subnautica.resources'),
        ),
    ]
