# Generated by Django 5.1.7 on 2025-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=300)),
                ('biome_type', models.CharField(max_length=50)),
                ('depth_range', models.IntegerField(default=0)),
                ('temp_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('obtain_from', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('biomes', models.ManyToManyField(related_name='resources_biomes', to='Subnautica.biomes')),
            ],
        ),
        migrations.AddField(
            model_name='biomes',
            name='resources',
            field=models.ManyToManyField(related_name='biomes_resources', to='Subnautica.resources'),
        ),
    ]
