# Generated by Django 5.2 on 2025-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subnautica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomes',
            name='depth_range',
            field=models.CharField(max_length=50),
        ),
    ]
