# Generated by Django 5.2 on 2025-04-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subnautica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biomes',
            old_name='biome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='resource',
            new_name='name',
        ),
    ]
