# Generated by Django 5.2 on 2025-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subnautica', '0002_alter_biomes_depth_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomes',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
