# Generated by Django 5.2 on 2025-04-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subnautica', '0003_tools_vehicles_faunas_eggs_floras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggs',
            old_name='locations',
            new_name='biomes',
        ),
    ]
