# Generated by Django 5.2 on 2025-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subnautica', '0003_alter_biomes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='build_time',
            field=models.CharField(max_length=50),
        ),
    ]
